import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.scss";

import Header from "@/components/organisms/Header/header";
import Footer from "@/components/organisms/Footer/footer";

const neueHaasGrotesk = localFont({
  src: [
    {
      path: "../../public/fonts/NeueHaasDisplayRoman.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/NeueHaasDisplayMedium.ttf",
      weight: "600",
      style: "normal",
    },
  ],
  display: "swap",
  variable: "--font-neue-haas-grotesk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={neueHaasGrotesk.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
